### ISSUE TITLE
Making sure I understand how the plugin is supposed to work

### ISSUE THREAD

**Issue by rvaneeuwijk** [uamanager/homebridge-calendar-scheduler#104]
Hi,

I have installed the plugin with the config shown below. I am getting two sensors in Apple Home: one called Calendar Test and one called Test. I created an event in the linked calendar called Test from 09:05 to 10:05. Do I understand correctly that this event should cause both sensors to open at 09:05 and to close at 10:05? The fact is that neither sensor opened since 09:00, when I last restarted the bridge. As you can see from the log below, nothing was logged for this plugin since that time.

Is this the expected behaviour given the config? If so, how would I get the sensors to open based on events in the linked calendar? Or am I completely misunderstanding the intended functionality of the plugin?

Thanks in advance!

**Configuration**
{
    "platform": "CalendarScheduler",
    "calendars": [
        {
            "calendarName": "Calendar Test",
            "calendarUrl": "webcal://p39-caldav.icloud.com/published/2/MjY5ODU2NzA2MjY5ODU2NyqwTRTGWxKvAbkzyE7YFRwH9G-lc2QaXpjjHNvlT8O5CcJ0PtEyG7U2xHec1i79BPQhXfLiGf2qITj6V8jNMTY",
            "calendarUpdateInterval": 1,
            "calendarUpdateButton": true,
            "calendarTriggerOnAllEvents": true,
            "calendarEvents": [
                {
                    "eventName": "Test"
                }
            ]
        }
    ]
}

**Log**
1/5/2023, 8:59:57 AMCalendar Scheduler Bridge starting
1/5/2023, 9:00:09 AMCalendar Scheduler BridgeLoaded plugin 'homebridge-calendar-scheduler'
1/5/2023, 9:00:09 AMCalendar Scheduler BridgeLoading 1 platforms...
1/5/2023, 9:00:09 AMCalendar Scheduler BridgeCalendarSchedulerFinished initializing platform: CalendarScheduler
1/5/2023, 9:00:11 AMCalendar Scheduler BridgeBridge is running on port 51916.

**Comment by uamanager** [comment]
First of all, better not use 1m interval for calendar updates. Continuous pulling of updates is pretty redundant.

Secondly, you shared logs only till 09:00:11, so I'm not able to understand what's wrong with your config.

Also I'm not able to check your calendar.

Please add debug property to calendar configuration, then we'll be able to understand what's wrong.
And if issue occurs, add screenshot of calendar event or better ics file of it.

**Comment by uamanager** [comment]
BTW make sure that eventName and name of calendar event are the same. Currently it's case-sensitive.

**Comment by uamanager** [comment]
That's great! 
It may be issue on iCloud side, as it may not update calendars right after local change.

In case of further issues try to use Google calendar. I works pretty well.

Also as a recommendation, use dedicated calendar just for automations, to decrease quantity of events, it should help with performance issues.

Stay safe! 🇺🇦
