### ISSUE TITLE
Sensor open before start of all-day event

### ISSUE THREAD

**Issue by rvaneeuwijk** [uamanager/homebridge-calendar-scheduler#105]
**Describe The Bug:**
My "Home Calendar", a public iCloud calendar, contains an all-day event called "Listed" tomorrow, but the contact sensor for events called "Listed" is already open in Apple HomeKit.

**To Reproduce:**
I have attached a screenshot of my "Home Calendar" and Apple Home app and pasted the plugin config and logs below.

**Expected behavior:**
 If I understand the plugin functionality correctly, the "Listed" event sensor should be closed until midnight.

**Logs:**
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Home Calendar] Get ActiveState On -> false
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Listed] Get ActiveState On -> false
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Listed Progress] Get ProgressState On -> 7
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Christmas Season] Get ActiveState On -> true
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Christmas Season Progress] Get ProgressState On -> 0.0001
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[AirBNB Test Event] Get ActiveState On -> true
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[AirBNB Test Event Progress] Get ProgressState On -> 0.0001
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Booked] Get ActiveState On -> false
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[Booked Progress] Get ProgressState On -> 52
1/6/2023, 10:19:13 PMCalendar Scheduler BridgeCalendarScheduler[AirBnB Edmonton] Get ActiveState On -> true

**Plugin Config:**
{
    "platform": "CalendarScheduler",
    "debug": true,
    "calendars": [
        {
            "calendarName": "Home Calendar",
            "calendarUrl": "webcal://p39-caldav.icloud.com/published/2/MjY5ODU2NzA2MjY5ODU2NyqwTRTGWxKvAbkzyE7YFRwH9G-lc2QaXpjjHNvlT8O5CcJ0PtEyG7U2xHec1i79BPQhXfLiGf2qITj6V8jNMTY",
            "calendarUpdateInterval": 1,
            "calendarUpdateButton": true,
            "calendarTriggerOnUpdates": true,
            "calendarTriggerOnAllEvents": true,
            "calendarEvents": [
                {
                    "eventName": "Christmas Season",
                    "eventTriggerOnUpdates": true
                },
                {
                    "eventName": "Booked",
                    "eventTriggerOnUpdates": true
                },
                {
                    "eventName": "Listed",
                    "eventTriggerOnUpdates": true
                }
            ]
        },
        {
            "calendarName": "AirBnB Edmonton",
            "calendarUrl": "MYAIRBNBCALENDAR",
            "calendarUpdateInterval": 60,
            "calendarUpdateButton": true,
            "calendarTriggerOnAllEvents": true,
            "calendarEvents": [
                {
                    "eventName": "AirBNB Test Event"
                }
            ]
        }
    ]
}

**Screenshots:**
Home Calendar: <img width="347" alt="Home Calendar Screenshot" src="https://user-images.githubusercontent.com/121703987/211132201-8d4350ad-1fcd-432a-9119-1d269eb47277.png">
Apple Home: 
<img width="1053" alt="Apple Home Screenshot" src="https://user-images.githubusercontent.com/121703987/211132386-1460af5d-b49b-40d8-9762-7ae1011cd436.png">

**Environment:**

* **Plugin Version**: 1.6.0
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.19.0
* **NPM Version**: unknown
* **Operating System**: Rasbian on HOOBS

**Comment by uamanager** [comment]
Hey, @rvaneeuwijk,

Thank you for this report. Accidentally plugin created switched for all events, which we shouldn't have at all. It's fixed in 1.6.1 patch.

**Comment by uamanager** [comment]
Hey, I leave this ticket open.

I've tested on my side all-day events and they are working without any issues.

Can you recreate such situation again? 
Maybe you renamed this `Booked` event (21:48) from `Listed` and scheduler not got updates from calendar?

**Comment by rvaneeuwijk** [comment]
Thanks for this. I upgraded to 1.6.1 and recreated the scenario for today and it now works as expected. Thank you! Slava ukraini for this too. ;-)
