### ISSUE TITLE
Event Notifications don't work

### ISSUE THREAD

**Issue by alexindigo** [uamanager/homebridge-calendar-scheduler#135]
**Describe The Bug:**

Tried to setup Event notifications to have offset time for turn on / off the sensor, but it not working, the main sensor is is turned on at the start of the event, and offset time is completely ignored.

**To Reproduce:**

I tried few different configurations, to no avail.

1. Event "Sora", Event Notification "Sora", start offset: -10, end offset: 10.

2. Event "Sora", Event Notification: "Sora Start", start offset: -10, end offset: --, Event Notification: "Sora End", start offset: --, end offset: 10.

3. Event "Sora", Event Notification: "SoraStart", start offset: -10, end offset: 10, Event Notification: "SoraEnd", start offset: -10, end offset: 10.

4. Event "Sora", Event Notification "SoraNotification", start offset: -10, end offset: 10. 

**Expected**

Expected to have sensor on 10 minutes before the event, and turned off 10 minutes after the event.

**Logs:**

```
[3/4/2023, 4:23:38 PM] [CalendarScheduler] Initializing CalendarScheduler platform...
[3/4/2023, 4:23:38 PM] [CalendarScheduler] Initializing child bridge 0E:
```

Not other Calendar logs in the Homebrdige status window

**Plugin Config:**

```json
{
    "caseInsensitiveEventsMatching": true,
    "debug": false,
    "calendars": [
        {
            "calendarName": "Online",
            "calendarUrl": "webcal://p31-<redacted>",
            "calendarUpdateInterval": 2,
            "calendarUpdateButton": false,
            "calendarTriggerOnUpdates": false,
            "calendarTriggerOnAllEvents": false,
            "caseInsensitiveEventsMatching": true,
            "calendarEvents": [
                {
                    "eventName": "Sora",
                    "eventTriggerOnUpdates": false,
                    "caseInsensitiveEventsMatching": false,
                    "calendarEventNotifications": [
                        {
                            "notificationName": "SoraNotification",
                            "notificationStartOffset": -10,
                            "notificationEndOffset": 10
                        }
                    ]
                }
            ]
        }
    ],
    "_bridge": {
        "username": "<redacted>",
        "port": <redacted>
    },
    "platform": "CalendarScheduler"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:  v2.1.2
* **Homebridge Version**: 1.6.0
* **Node.js Version**: v18.13.0
* **NPM Version**: 8.19.3
* **Operating System**: Ubuntu 20.04.5 LTS (Docker)

**Comment by uamanager** [comment]
Hey, @alexindigo 
Thank you for your issue, it seems like documentation is not clear enough on how notifications working and how to configure them properly.

Notifications not changing starting or ending time of calendar event, as it can lead to misunderstanding on how event should be handled. Instead plugin creates additional accessory for each notification and triggers it depending on provided offsets. Name of notification used for accessory name.

Also notification configuration supports only one of the offsets and when configuring both only start one would be used.

Your configuration should look like this:

```
{
    "caseInsensitiveEventsMatching": true,
    "debug": false,
    "calendars": [
        {
            "calendarName": "Online",
            "calendarUrl": "webcal://p31-<redacted>",
            "calendarUpdateInterval": 2,
            "calendarUpdateButton": false,
            "calendarTriggerOnUpdates": false,
            "calendarTriggerOnAllEvents": false,
            "caseInsensitiveEventsMatching": true,
            "calendarEvents": [
                {
                    "eventName": "Sora",
                    "eventTriggerOnUpdates": false,
                    "caseInsensitiveEventsMatching": false,
                    "calendarEventNotifications": [
                        {
                            "notificationName": "SoraStartNotification",
                            "notificationStartOffset": -10
                        },
                        {
                            "notificationName": "SoraEndNotification",
                            "notificationEndOffset": 10
                        }
                    ]
                }
            ]
        }
    ],
    "_bridge": {
        "username": "<redacted>",
        "port": <redacted>
    },
    "platform": "CalendarScheduler"
}
```

Using this config, plugin will create two accessories with names:
- `SoraStartNotification` for notification 10 minutes before event start
- `SoraEndNotification` for notification 10 minutes after event end

Hope this answer is helpful and would solve your issue.

Stay Safe!

**Comment by alexindigo** [comment]
Thanks for the quick response.

Yep, I've tried that setup us as well

> 2. Event "Sora", Event Notification: "Sora Start", start offset: -10, end offset: --, Event Notification: "Sora End", start offset: --, end offset: 10.

And I did pay attention to the new sensors that showed up, but they never turned on.
(This is why I started experimenting with further options).

Also what is not clear, for that new sensors:

`SoraStartNotification` - if it turns on 10 minutes before, when would it turn off, right away, or same time as the main event?

`SoraEndNotification` - if it turns off 10 minutes after, when would it turn on? Same time as the main event, or just a second before?

And in general why it needs to be two different events?
How about?

```
                    "calendarEventNotifications": [
                        {
                            "notificationName": "SoraNotification",
                            "notificationStartOffset": -10
                            "notificationEndOffset": 10
                        }
                    ]
```


And I'd love to better understand what do you mean by "it can lead to misunderstanding on how event should be handled", as just having two simple fields "activate minutes before" and "deactivate minutes after" – would be very clear for users what's going on, and all the "operational complexity" could be handled under the hood, as this is the only information plugin needs to understand what user wants. And just exposing single sensor that would be activate said minutes before and deactivated said minutes after would make it very intuitive how to use it, rather than trying to catching new sensors.

**Comment by uamanager** [comment]
Notification sensors are flicking their state, it may not be visible from Home app UI but it works if Home app has automation bound to notification sensors.

The idea was to use same approach as calendar notifications do - notify  user automation about calendar event start or end time with before or after offsets.

Separate notifications are required for several reasons:
- Single responsibility of notification. Notification is used for binding automation to them and for complex scenarios it's crucial to be able to determine which notification accessory changed state and why.
- More use-cases. Such notifications allows to have non-fixed list of notifications, which again is useful for complex automations. 
- No event mutation. Event states unchanged and it allows to track it's progress with or without notifications configured.

So to be clear on how calendar event accessory tracks progress and at which time it enabled or disabled, notification separated into their own accessories, it adds more advantages than disadvantages and unlocks variety of scenarios to use.

**Comment by alexindigo** [comment]
Thanks for the details. I think my philosophy is somewhat different – solving simple problems in a simple way first, then adding advanced options, but I understand – it's your vision.

How about that secondary sensors, if both start and end offsets provided would just stay on during the whole event + offset times? It would still allow for all the features you described, but also, make simple use cases straightforward and intiuitive?

And speaking of automation and single responsibilities – the reason I started experimenting with different configs – because that usage that you described didn't work, I had setup as example 2:

> Event "Sora", Event Notification: "Sora Start", start offset: -10, end offset: --, Event Notification: "Sora End", start offset: --, end offset: 10.

And it didn't turn on. I had automation attached to "Sora Start" when it opens would would turn on plug where portal was connected to, and it didn't work. So maybe not only me didn't catch it, but Homekit itself wasn't able to use it as trigger.

**Comment by uamanager** [comment]
Let me check issue by myself, as I tested everything before publishing.

Also please create feature request with detailed description of use-cases and possible solution.

**Comment by uamanager** [comment]
I increased timer to be 10 secs instead of 1 to give home app more time for getting accessory updates.
