### ISSUE TITLE
Unicode Calendar Events don't work.

### ISSUE THREAD

**Issue by dsully** [uamanager/homebridge-calendar-scheduler#142]
**Describe The Bug:**
If you setup an event match with unicode characters the regex here:

https://github.com/uamanager/homebridge-calendar-scheduler/blob/master/src/configs/event.config.ts#L33

Will strip them out, possibly leaving an empty string and putting `homebridge` into a restart loop.

By changing `safeEvent` to `eventName` here:

https://github.com/uamanager/homebridge-calendar-scheduler/blob/master/src/calendar.handler.ts#L100

Everything works.

**Plugin Config:**

```json
{
            "caseInsensitiveEventsMatching": false,
            "debug": false,
            "calendars": [
                {
                    "calendarName": "Calendar",
                    "calendarUrl": "webcal://p101-caldav.icloud.com/...",
                    "calendarUpdateInterval": 60,
                    "calendarUpdateButton": true,
                    "calendarTriggerOnUpdates": false,
                    "calendarTriggerOnAllEvents": true,
                    "caseInsensitiveEventsMatching": true,
                    "calendarEvents": [
                        {
                            "eventName": "😎",
                            "eventTriggerOnUpdates": false,
                            "caseInsensitiveEventsMatching": false,
                            "calendarEventNotifications": [
                                {
                                    "notificationName": "TurnOn",
                                    "notificationStartOffset": -45
                                }
                            ]
                        }
                    ]
                }
            ],
            "platform": "CalendarScheduler",
            "_bridge": {
                "username": "0E:32:8A:D1:92:1A",
                "port": 54101
            }
        }
```

**Comment by uamanager** [comment]
Hey, thanks for reporting this bug!
Seems like it's really removing unicode symbols and leaving empty string. The idea was to remove everything that could be wrong from homekit standpoint, but it caused such issue.
Let me think on how it can be fixed without impact on those who doesn't use emojis in name.

**Comment by dsully** [comment]
Thanks. Were there specific characters that were causing issues in HomeKit?

**Comment by uamanager** [comment]
HomeKit accessory name can not contain special characters or emoji, so I assume that id's also should not contain them.

**Comment by dsully** [comment]
With the change I did above, it created an accessory with the emoji no problem.

**Comment by uamanager** [comment]
Sure, It creates accessories using Homebridge, but it doesn't mean that such symbols are not allowed. Try to change accessory name from Home application.

I'll think about fix and notify you as soon as it'll be released.

**Comment by dsully** [comment]
I see what you mean now. You can't modify the name in Home (or say the Eve) app. But Homebridge via your plugin can create those accessories.

**Comment by uamanager** [comment]
Sure, but I'd prefer not to go against rules even if I can in such workaround way.

**Comment by uamanager** [comment]
I've added additional config property `unsafeEventNames` on each level of configuration, so you can enable it globally, for calendar or for concrete event. It'll allow you to use unicode symbols and won't touch event name at all.

**Comment by dsully** [comment]
Thanks - I'll give that a try.
