### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by drdante01** [uamanager/homebridge-calendar-scheduler#235]
**Describe Your Problem:**
I am encountering an `ETIMEDOUT` error while updating the calendar in Homebridge. The error specifies that it is unable to connect to server 188.114.97.6 on port 443. I have verified using online tools that port 443 on the specified server is currently closed. 

**Logs:**

```
Error while updating calendar: Prayer Time Error: connect ETIMEDOUT 188.114.97.6:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '188.114.97.6',
  port: 443
}
```

**Plugin Config:**

```json
{
    "caseInsensitiveEventsMatching": false,
    "unsafeEventNames": false,
    "debug": true,
    "calendars": [
        {
            "calendarName": "Prayer Time",
            "calendarUrl": "https://prayerwebcal.dsultan.com",
            "calendarUpdateInterval": 60,
            "calendarUpdateButton": true,
            "calendarTriggerOnUpdates": true,
            "calendarTriggerOnAllEvents": true,
            "caseInsensitiveEventsMatching": false,
            "unsafeEventNames": false,
            "calendarEvents": [
                {
                    "eventName": "event-name1",
                    "eventTriggerOnUpdates": true,
                    "caseInsensitiveEventsMatching": false,
                    "unsafeEventNames": false,
                    "calendarEventNotifications": [
                        {
                            "notificationName": "notification-name1"
                        }
                    ]
                }
            ]
        }
    ],
    "_bridge": {
        "username": "0E:E4:CE:35:33:0F",
        "port": 35664
    },
    "platform": "CalendarScheduler"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v2.2.1
* **Homebridge Version**: v4.50.5
* **Node.js Version**: v18.15.0
* **NPM Version**: 9.6.2
* **Operating System**: Windows

**Comment by uamanager** [comment]
Hey, it seems like you are trying to use website url and not the ical one.

Website that you mentioned suggests to use links like this: `https://prayerwebcal.dsultan.com/ics/New_York_NY_USA/tz=America%2FNew_York`

**Comment by drdante01** [comment]
Yes, I know. I removed the location for privacy reasons

**Comment by uamanager** [comment]
I finally found the time to check this issue.

I've added calendar configuration:
```json
{
  "calendarName": "Prayer Time",
  "calendarUrl": "https://prayerwebcal.dsultan.com/ics/Kiev_Ukraine/tz=Europe%2FKiev:x=50.43:y=30.52",
  "calendarUpdateInterval": 60,
  "calendarUpdateButton": true,
  "calendarTriggerOnUpdates": false,
  "calendarTriggerOnAllEvents": true,
  "caseInsensitiveEventsMatching": false,
  "unsafeEventNames": false
}
```

Configuration is pretty simple and it just enables calendar accessory if there is any active event.

I see no issues with fetching the calendar or reading it:

<img width="192" alt="image" src="https://github.com/uamanager/homebridge-calendar-scheduler/assets/2138444/d5fdd606-d91c-4740-a135-2da5ee9780c3">

So, I suspect the problem might just be connection issues on your end.

Let me know if I can further assist you with this plugin.
