### ISSUE TITLE
Trigger notification on any active event

### ISSUE THREAD

**Issue by matthiascreinartz** [uamanager/homebridge-calendar-scheduler#287]
**Is your feature request related to a problem? Please describe:**
As a user I want to be able to trigger notifications on any given event regardless of the title.

**Describe the solution you'd like:**
An option for notifications alike to calender-option "Trigger on any active events or only on defined active events".
If set to true, the defined notifications will trigger regardless of the events title.

In that way it doesn't matter how the meeting is called. Just every time any meeting occurs the defined notifications will be triggered.

**Additional context**
I am using the calendar solely for planning meetings. But each meetings has a totally different title depending on who is meeting for what reason.

**Comment by matthiascreinartz** [comment]
I didn't think of using regexp - thanks: that works perfectly for me.

**Comment by uamanager** [comment]
Feel free to reopen issue in case of any issues.
