### ISSUE TITLE
Event Time Offset

### ISSUE THREAD

**Issue by mrtzlbm** [uamanager/homebridge-calendar-scheduler#72]
Hi Ivan, 
have you considered adding an offset parameter to trigger for an event before or after a calendar event takes place?

**Example usecase:** I want to preheat my coffee maschine before my workday starts which is indicated by a event in my calendar. 

Thanks for considering!

**Comment by uamanager** [comment]
Hey, thank you for interest!

That's pretty interesting idea, I definitely should add this functionality in next release.

**Comment by uamanager** [comment]
Hey @mrtzlbm,
I've added `calendarOffset` property in latest release, it allows to add offset for all calendar events. Be careful, it works for both start and end of event.

I'm going to add eventNotifications configuration in the future to allow notify before or after event start/end but for now added property should be enough.

**Comment by mrtzlbm** [comment]
Hi @uamanager,
awesome! Thank you for implementing this. I will try it asap.

**Comment by alexindigo** [comment]
Another idea along the same lines, is to have separate / different offset for before after event time.
My use case, I was to turn on plug with my kid's portal before her online class, would need time to boot up – 5 minutes before the event, and turn off after class is done – don't really want it to be turned off 5 minutes before class is over, as it would work in the current version, rather I'd like to be able to turn it off 10 minutes after class is over, to account for possible delays – need negative offset for "after" the event.

And while we at it, custom offset per event would be very useful, as it will allow to create event specific scenarios.

Thank you.

**Comment by uamanager** [comment]
@alexindigo Sure, that's what I'm planning to implement at the end. Calendar offset is more like temporary workaround and timezone offset feature.

I'll notify everyone in this issue about feature readiness.

Thanks for sharing your scenario of plugin usage)

**Comment by uamanager** [comment]
Hey @mrtzlbm and @alexindigo!
I've finally delivered notification feature, it's available in version 2.0.1

Here are some examples on how to use it:

```json lines
{
  // calendar configuration
  "calendarEvents": [
    {
      // event configuration
      "calendarEventNotifications": [
        {
          // notification will be triggered 15 minutes before event start
          "notificationName": "event-notification-name-before-start-15m",
          "notificationStartOffset": -15
        },
        {
          // notification will be triggered 15 minutes after event start
          "notificationName": "event-notification-name-after-start-15m",
          "notificationStartOffset": 15
        },
        {
          // notification will be triggered 15 minutes before event end
          "notificationName": "event-notification-name-before-end-15m",
          "notificationEndOffset": -15
        },
        {
          // notification will be triggered 15 minutes after event end
          "notificationName": "event-notification-name-after-end-15m",
          "notificationEndOffset": 15
        }
      ]
    }
  ]
}
```

Maximum notification offset is +/-60 minutes, otherwise it defaults to +/-60 respectively.

Keep in mind that `calendarOffset` option is removed in favour of notifications feature.

Thank you for this feature report and your use-cases!

Stay safe🇺🇦

**Comment by mrtzlbm** [comment]
Hi @uamanager!
Thank you so much for your work, the notification system is really cool and offers a lot of customization, truly great work on your part!
Just curious, why is the max offset 60 minutes? I actually have a usecase where I'd like to preheat my coffee machine, starting 2h before an event starts.
Thanks again, stay safe!

Slava Ukraini! 🇺🇦

**Comment by uamanager** [comment]
It's easy to adjust) 60 minutes because initially I was going to use not the best option from performance point of view for calculating active events.
Let me apply quick update and increase it to 24h.

**Comment by uamanager** [comment]
@mrtzlbm Restriction removed, so feel free to configure any offset in minutes

Heroyam Slava!🇺🇦

**Comment by alexindigo** [comment]
Woah! Thanks a lot for the quick update.
With these new features I'll be using even more calendar powered functionality.
