### ISSUE TITLE
Ignore case on event titles

### ISSUE THREAD

**Issue by xxKeoxx** [uamanager/homebridge-calendar-scheduler#99]
Would it be possible to get this to ignore case on calendar event titles?  I find that my wife often gets the case wrong when she adds the event title and this causes the automation to fail.

**Comment by uamanager** [comment]
@xxKeoxx Do you prefer to make it configurable per calendar or as a global configuration property? Or maybe both?

**Comment by xxKeoxx** [comment]
Which ever is easiest to implement.

**Comment by uamanager** [comment]
Hey, @xxKeoxx!

I just released new version of this plugin.
New configuration property is now available in Calendar Config. After update you're able to set `caseInsensitiveEventsMatching` property to `true` on any levels of configuration. Keep in mind that if top level configuration set to be case-insensitive, then children configurations are also case-insensitive.
So you're able to set case-insensitivity globally, per calendar or per event.   

Let me know if something is not clear or works not as you expect.

Appreciate your interest to plugin and thank you for this feature request!

Stay safe! 🇺🇦
